version: '3.8'

services:


  cli:
    build: ./cli
    volumes:
      - ..:/workspaces/laravel

  fpm:
    build: ./fpm
    volumes:
      - ..:/workspaces/laravel

  nginx:
    build: ./nginx
    volumes:
      - ..:/workspaces/laravel
    ports:
      - "8000:80"
    depends_on:
      - fpm
      - db

  db:
    platform: "linux/amd64"
    image: mysql:5.7
    env_file:
      - ../.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7.2-alpine
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  dbdata:
